// The sandbox service contract.
//
// This file is the single source for both implementations. The transitional
// Python control plane and the Go service that replaces it generate from it, so
// the two cannot drift while they coexist, and the SDK speaks one wire format
// throughout.
//
// Two rules shape it.
//
//   - Command and file traffic are absent on purpose. A create returns the
//     resolved agent endpoint and the SDK talks to the sandbox directly, because
//     an episode issues dozens of commands and a control plane in that path adds
//     a hop and a serialization without making a decision.
//   - A failure is typed by attribution rather than by where it happened. An
//     infrastructure fault that arrives as a task result would be recorded as a
//     model or harness failure and would corrupt a reward.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: api/v1/sandbox.proto

package sandboxv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SandboxControl_Create_FullMethodName         = "/psrl.sandbox.v1.SandboxControl/Create"
	SandboxControl_CreateGroup_FullMethodName    = "/psrl.sandbox.v1.SandboxControl/CreateGroup"
	SandboxControl_Restore_FullMethodName        = "/psrl.sandbox.v1.SandboxControl/Restore"
	SandboxControl_Status_FullMethodName         = "/psrl.sandbox.v1.SandboxControl/Status"
	SandboxControl_Diagnostics_FullMethodName    = "/psrl.sandbox.v1.SandboxControl/Diagnostics"
	SandboxControl_Pause_FullMethodName          = "/psrl.sandbox.v1.SandboxControl/Pause"
	SandboxControl_Resume_FullMethodName         = "/psrl.sandbox.v1.SandboxControl/Resume"
	SandboxControl_Snapshot_FullMethodName       = "/psrl.sandbox.v1.SandboxControl/Snapshot"
	SandboxControl_DeleteSnapshot_FullMethodName = "/psrl.sandbox.v1.SandboxControl/DeleteSnapshot"
	SandboxControl_Release_FullMethodName        = "/psrl.sandbox.v1.SandboxControl/Release"
	SandboxControl_Fleet_FullMethodName          = "/psrl.sandbox.v1.SandboxControl/Fleet"
	SandboxControl_Quota_FullMethodName          = "/psrl.sandbox.v1.SandboxControl/Quota"
)

// SandboxControlClient is the client API for SandboxControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// What a caller asks a fleet for. One create, one release, and the state
// operations; everything else happens against the sandbox itself.
type SandboxControlClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// A group is a completion unit rather than a scheduling unit, so members are
	// admitted independently and no member holds capacity while a sibling queues.
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Status(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*StatusResponse, error)
	Diagnostics(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*DiagnosticsResponse, error)
	Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*Empty, error)
	Resume(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*Empty, error)
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotRef, error)
	DeleteSnapshot(ctx context.Context, in *SnapshotRef, opts ...grpc.CallOption) (*Empty, error)
	Release(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*Empty, error)
	// Reports for the caller's metric hook. The planes report and never log.
	Fleet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FleetReport, error)
	Quota(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuotaReport, error)
}

type sandboxControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxControlClient(cc grpc.ClientConnInterface) SandboxControlClient {
	return &sandboxControlClient{cc}
}

func (c *sandboxControlClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, SandboxControl_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, SandboxControl_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, SandboxControl_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Status(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SandboxControl_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Diagnostics(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*DiagnosticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiagnosticsResponse)
	err := c.cc.Invoke(ctx, SandboxControl_Diagnostics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Pause(ctx context.Context, in *PauseRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SandboxControl_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Resume(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SandboxControl_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotRef, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotRef)
	err := c.cc.Invoke(ctx, SandboxControl_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) DeleteSnapshot(ctx context.Context, in *SnapshotRef, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SandboxControl_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Release(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SandboxControl_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Fleet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FleetReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FleetReport)
	err := c.cc.Invoke(ctx, SandboxControl_Fleet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxControlClient) Quota(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*QuotaReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotaReport)
	err := c.cc.Invoke(ctx, SandboxControl_Quota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxControlServer is the server API for SandboxControl service.
// All implementations must embed UnimplementedSandboxControlServer
// for forward compatibility.
//
// What a caller asks a fleet for. One create, one release, and the state
// operations; everything else happens against the sandbox itself.
type SandboxControlServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// A group is a completion unit rather than a scheduling unit, so members are
	// admitted independently and no member holds capacity while a sibling queues.
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	Restore(context.Context, *RestoreRequest) (*CreateResponse, error)
	Status(context.Context, *SandboxHandle) (*StatusResponse, error)
	Diagnostics(context.Context, *SandboxHandle) (*DiagnosticsResponse, error)
	Pause(context.Context, *PauseRequest) (*Empty, error)
	Resume(context.Context, *SandboxHandle) (*Empty, error)
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotRef, error)
	DeleteSnapshot(context.Context, *SnapshotRef) (*Empty, error)
	Release(context.Context, *SandboxHandle) (*Empty, error)
	// Reports for the caller's metric hook. The planes report and never log.
	Fleet(context.Context, *Empty) (*FleetReport, error)
	Quota(context.Context, *Empty) (*QuotaReport, error)
	mustEmbedUnimplementedSandboxControlServer()
}

// UnimplementedSandboxControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxControlServer struct{}

func (UnimplementedSandboxControlServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSandboxControlServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedSandboxControlServer) Restore(context.Context, *RestoreRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedSandboxControlServer) Status(context.Context, *SandboxHandle) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSandboxControlServer) Diagnostics(context.Context, *SandboxHandle) (*DiagnosticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Diagnostics not implemented")
}
func (UnimplementedSandboxControlServer) Pause(context.Context, *PauseRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedSandboxControlServer) Resume(context.Context, *SandboxHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedSandboxControlServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotRef, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedSandboxControlServer) DeleteSnapshot(context.Context, *SnapshotRef) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedSandboxControlServer) Release(context.Context, *SandboxHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedSandboxControlServer) Fleet(context.Context, *Empty) (*FleetReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fleet not implemented")
}
func (UnimplementedSandboxControlServer) Quota(context.Context, *Empty) (*QuotaReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Quota not implemented")
}
func (UnimplementedSandboxControlServer) mustEmbedUnimplementedSandboxControlServer() {}
func (UnimplementedSandboxControlServer) testEmbeddedByValue()                        {}

// UnsafeSandboxControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxControlServer will
// result in compilation errors.
type UnsafeSandboxControlServer interface {
	mustEmbedUnimplementedSandboxControlServer()
}

func RegisterSandboxControlServer(s grpc.ServiceRegistrar, srv SandboxControlServer) {
	// If the following call pancis, it indicates UnimplementedSandboxControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxControl_ServiceDesc, srv)
}

func _SandboxControl_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Status(ctx, req.(*SandboxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Diagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Diagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Diagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Diagnostics(ctx, req.(*SandboxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Pause(ctx, req.(*PauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Resume(ctx, req.(*SandboxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).DeleteSnapshot(ctx, req.(*SnapshotRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Release(ctx, req.(*SandboxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Fleet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Fleet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Fleet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Fleet(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxControl_Quota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxControlServer).Quota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxControl_Quota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxControlServer).Quota(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxControl_ServiceDesc is the grpc.ServiceDesc for SandboxControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "psrl.sandbox.v1.SandboxControl",
	HandlerType: (*SandboxControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SandboxControl_Create_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _SandboxControl_CreateGroup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _SandboxControl_Restore_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _SandboxControl_Status_Handler,
		},
		{
			MethodName: "Diagnostics",
			Handler:    _SandboxControl_Diagnostics_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _SandboxControl_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _SandboxControl_Resume_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _SandboxControl_Snapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _SandboxControl_DeleteSnapshot_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _SandboxControl_Release_Handler,
		},
		{
			MethodName: "Fleet",
			Handler:    _SandboxControl_Fleet_Handler,
		},
		{
			MethodName: "Quota",
			Handler:    _SandboxControl_Quota_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/sandbox.proto",
}

const (
	SandboxNode_Admit_FullMethodName     = "/psrl.sandbox.v1.SandboxNode/Admit"
	SandboxNode_CreateOn_FullMethodName  = "/psrl.sandbox.v1.SandboxNode/CreateOn"
	SandboxNode_ReleaseOn_FullMethodName = "/psrl.sandbox.v1.SandboxNode/ReleaseOn"
	SandboxNode_Report_FullMethodName    = "/psrl.sandbox.v1.SandboxNode/Report"
	SandboxNode_Sweep_FullMethodName     = "/psrl.sandbox.v1.SandboxNode/Sweep"
)

// SandboxNodeClient is the client API for SandboxNode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// What one node offers the control plane. A node keeps final admission
// authority, so a Placement decision is a proposal and this is where it is
// accepted or refused against live local pressure.
type SandboxNodeClient interface {
	Admit(ctx context.Context, in *AdmitRequest, opts ...grpc.CallOption) (*AdmitResponse, error)
	CreateOn(ctx context.Context, in *CreateOnRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	ReleaseOn(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*Empty, error)
	Report(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeView, error)
	Sweep(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SweepReport, error)
}

type sandboxNodeClient struct {
	cc grpc.ClientConnInterface
}

func NewSandboxNodeClient(cc grpc.ClientConnInterface) SandboxNodeClient {
	return &sandboxNodeClient{cc}
}

func (c *sandboxNodeClient) Admit(ctx context.Context, in *AdmitRequest, opts ...grpc.CallOption) (*AdmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdmitResponse)
	err := c.cc.Invoke(ctx, SandboxNode_Admit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxNodeClient) CreateOn(ctx context.Context, in *CreateOnRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, SandboxNode_CreateOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxNodeClient) ReleaseOn(ctx context.Context, in *SandboxHandle, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SandboxNode_ReleaseOn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxNodeClient) Report(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeView, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeView)
	err := c.cc.Invoke(ctx, SandboxNode_Report_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sandboxNodeClient) Sweep(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SweepReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SweepReport)
	err := c.cc.Invoke(ctx, SandboxNode_Sweep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SandboxNodeServer is the server API for SandboxNode service.
// All implementations must embed UnimplementedSandboxNodeServer
// for forward compatibility.
//
// What one node offers the control plane. A node keeps final admission
// authority, so a Placement decision is a proposal and this is where it is
// accepted or refused against live local pressure.
type SandboxNodeServer interface {
	Admit(context.Context, *AdmitRequest) (*AdmitResponse, error)
	CreateOn(context.Context, *CreateOnRequest) (*CreateResponse, error)
	ReleaseOn(context.Context, *SandboxHandle) (*Empty, error)
	Report(context.Context, *Empty) (*NodeView, error)
	Sweep(context.Context, *Empty) (*SweepReport, error)
	mustEmbedUnimplementedSandboxNodeServer()
}

// UnimplementedSandboxNodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSandboxNodeServer struct{}

func (UnimplementedSandboxNodeServer) Admit(context.Context, *AdmitRequest) (*AdmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Admit not implemented")
}
func (UnimplementedSandboxNodeServer) CreateOn(context.Context, *CreateOnRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOn not implemented")
}
func (UnimplementedSandboxNodeServer) ReleaseOn(context.Context, *SandboxHandle) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseOn not implemented")
}
func (UnimplementedSandboxNodeServer) Report(context.Context, *Empty) (*NodeView, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}
func (UnimplementedSandboxNodeServer) Sweep(context.Context, *Empty) (*SweepReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sweep not implemented")
}
func (UnimplementedSandboxNodeServer) mustEmbedUnimplementedSandboxNodeServer() {}
func (UnimplementedSandboxNodeServer) testEmbeddedByValue()                     {}

// UnsafeSandboxNodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SandboxNodeServer will
// result in compilation errors.
type UnsafeSandboxNodeServer interface {
	mustEmbedUnimplementedSandboxNodeServer()
}

func RegisterSandboxNodeServer(s grpc.ServiceRegistrar, srv SandboxNodeServer) {
	// If the following call pancis, it indicates UnimplementedSandboxNodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SandboxNode_ServiceDesc, srv)
}

func _SandboxNode_Admit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxNodeServer).Admit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxNode_Admit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxNodeServer).Admit(ctx, req.(*AdmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxNode_CreateOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxNodeServer).CreateOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxNode_CreateOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxNodeServer).CreateOn(ctx, req.(*CreateOnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxNode_ReleaseOn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SandboxHandle)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxNodeServer).ReleaseOn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxNode_ReleaseOn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxNodeServer).ReleaseOn(ctx, req.(*SandboxHandle))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxNode_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxNodeServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxNode_Report_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxNodeServer).Report(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SandboxNode_Sweep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SandboxNodeServer).Sweep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SandboxNode_Sweep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SandboxNodeServer).Sweep(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SandboxNode_ServiceDesc is the grpc.ServiceDesc for SandboxNode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SandboxNode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "psrl.sandbox.v1.SandboxNode",
	HandlerType: (*SandboxNodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Admit",
			Handler:    _SandboxNode_Admit_Handler,
		},
		{
			MethodName: "CreateOn",
			Handler:    _SandboxNode_CreateOn_Handler,
		},
		{
			MethodName: "ReleaseOn",
			Handler:    _SandboxNode_ReleaseOn_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _SandboxNode_Report_Handler,
		},
		{
			MethodName: "Sweep",
			Handler:    _SandboxNode_Sweep_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/sandbox.proto",
}
