import logging
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Generic, TypeVar

import torch
import numpy as np
import ray
from omegaconf import DictConfig
from verl.utils import tensordict_utils as tu
from verl.utils.ray_utils import get_event_loop

from psrl.environments.base import ConversationType, Environment
from psrl.workers.gen_dplb.utils import RolloutInstanceId, TokenOutput

psrl_logger = logging.getLogger(__name__)
psrl_logger.setLevel(os.getenv("PSRL_LOGGING_LEVEL", "WARN"))


@dataclass
class Step:
    """
    Represents a single step in an agent's trajectory during rollout.

    This class encapsulates all information about one interaction step, including
    the conversation state, model response, action taken, and associated rewards.
    """

    # List of conversation messages at this step
    chat_completions: ConversationType = field(default_factory=list)

    # Environment observation received at this step
    observation: Any = None
    # Internal reasoning or thought process (if applicable)
    thought: str = ""
    # Action taken by the agent at this step
    action: Any = None
    # Raw text response generated by the model
    model_response: str = ""
    # Additional metadata or debug information
    info: dict = field(default_factory=dict)

    # Reward from tool execution (if applicable)
    tool_reward: list[float] | None = None
    # Reward from model evaluation (if applicable)
    model_reward: float | None = None
    # Combined or final reward for this step
    reward: float | None = None
    # Whether this step terminates the episode
    done: bool = False

    def to_dict(self) -> dict:
        """Convert the step to a dictionary representation.

        Returns:
            dict: Dictionary containing all step attributes.
        """
        return {
            "chat_completions": self.chat_completions,
            "observation": self.observation,
            "thought": self.thought,
            "action": self.action,
            "model_response": self.model_response,
            "info": self.info,
            "tool_reward": self.tool_reward,
            "model_reward": self.model_reward,
            "reward": self.reward,
            "done": self.done,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Step":
        """Create a Step instance from a dictionary.

        Args:
            data: Dictionary containing step attributes.

        Returns:
            Step: New Step instance initialized with data from dictionary.
        """
        return cls(
            chat_completions=data.get("chat_completions", []),
            observation=data.get("observation"),
            thought=data.get("thought", ""),
            action=data.get("action"),
            model_response=data.get("model_response", ""),
            info=data.get("info", {}),
            tool_reward=data.get("tool_reward", []),
            model_reward=data.get("model_reward", 0.0),
            reward=data.get("reward", 0.0),
            done=data.get("done", False),
        )


@dataclass
class Trajectory:
    # List of Step objects comprising this trajectory
    steps: list[Step] = field(default_factory=list)
    # Number of assistant (model) turns taken
    assistant_turns: int = 0
    # Number of user (environment) turns taken
    user_turns: int = 0
    # Total reward accumulated for this trajectory
    reward: float | None = None
    # Total length of generated responses in tokens
    response_length: int = 0

    # State variables
    prompt_ids: list[int] = field(default_factory=list)
    response_ids: list[int] = field(default_factory=list)
    response_mask: list[int] = field(default_factory=list)
    response_logprobs: list[float] = field(default_factory=list)
    routed_experts: list[int] = field(default_factory=list)

    # Per-turn reward signals
    # Rewards collected from tool execution at each user turn.
    tool_rewards: list[float] = field(default_factory=list)
    # Rewards collected from an Interaction at each user turn (e.g. human feedback).
    turn_scores: list[float] = field(default_factory=list)

    # Multi-modal data accumulated across turns.
    # image_data: list of PIL.Image.Image (or any image objects accepted by the processor).
    # video_data: list of (video_tensor, metadata) tuples.
    image_data: list[Any] | None = None
    video_data: list[Any] | None = None
    
    # Arbitrary extra fields for dynamic addition (e.g. tools_kwargs, interaction_kwargs).
    extra_fields: dict = field(default_factory=dict)

@dataclass
class SessionData:
    """
    Represents a complete session of agent interactions.

    A session contains multiple trajectories and tracks the cumulative state and rewards
    throughout an episode. It includes both the conversation history and tokenized
    representations for model training.
    """

    # Unique identifier for this session
    request_id: int = 0
    # ID of parent session (for group-based generation)
    parent_id: int | None = None
    # Current rollout instance ID
    curr_rollout_instance_id: RolloutInstanceId | None = None
    # val/train session data
    validate: bool = False

    # NOTE(linsh): the source of the following three fileds is dataset
    # Data source of current session
    data_source: str = "unknown"
    # Reward model info (e.g., ground truth)
    reward_model: dict = field(default_factory=dict)
    # Extra info of input request
    extra_info: dict = field(default_factory=dict)
    # List of reward model dict
    reward_model_dicts: list[dict] = field(default_factory=list)

    # List of Step objects comprising this trajectory
    steps: list[Step] = field(default_factory=list)
    # Number of assistant (model) turns taken
    assistant_turns: int = 0
    # Number of user (environment) turns taken
    user_turns: int = 0
    # Total reward accumulated for this trajectory
    reward: float | None = None
    # Total length of generated responses in tokens
    response_length: int = 0
    # Additional metadata or debug information
    info: dict = field(default_factory=dict)

    # Trajectories inside a session
    trajectories: list[Trajectory] = field(default_factory=list)

ObsType = TypeVar("ObsType")
ActType = TypeVar("ActType")


class AgentData(ABC, Generic[ObsType, ActType]):
    """
    Abstract base class for managing agent trajectory data during rollout.

    This class handles the state and data flow during agent-environment interactions,
    including trajectory initialization, updates from model/environment, reward computation,
    and preparation of training data. Subclasses should implement specific logic for
    different interaction formats (e.g., tool-based, conversational).

    Type Parameters:
        ObsType: Type of observations received from the environment
        ActType: Type of actions taken by the agent
    """

    _registry: dict[str, type["AgentData"]] = {}
    _class_initialized = False

    def __init__(
        self,
        config: DictConfig,
        reward_manager: ray.actor.ActorHandle,
        env: Environment,
        **kwargs,
    ):
        """Initialize the AgentData instance.

        Args:
            config: Configuration object containing training settings
            reward_manager: Ray actor handle for computing rewards
            env: Environment instance this agent interacts with
            **kwargs: Additional keyword arguments from configuration
        """
        self.init_class(config=config, **kwargs)
        self.config = config
        self.reward_manager = reward_manager
        self.env = env
        self.tokenizer = self.env.tokenizer
        self.processor = self.env.processor
        self.session_data = SessionData()
        self.loop = get_event_loop()

        # Discount factor for reward discounting (default: 0.0)
        self.gamma = self.config.gen_actor_rollout_ref.rollout.agent.gamma
        # Coefficient for reward shaping (default: 0.0)
        self.reward_bonus_coeff = self.config.gen_actor_rollout_ref.rollout.agent.reward_bonus_coeff

    @classmethod
    def init_class(cls, config: DictConfig, **kwargs):
        """This is used to do heavy initialization work that should shared across all instances. It's only called once.

        Args:
            config (DictConfig): trainer config.
            tokenizer (AutoTokenizer): Tokenizer for tokenize messages.
            **kwargs: extra kwargs from config file passed in by `hydra.utils.instantiate`.
        """
        if cls._class_initialized:
            return
        cls._class_initialized = True

    def create_trajectory(self):
        self.session_data.trajectories.append(Trajectory())

    def start_step(self, observation: ObsType, reward: list[float] | None, done: bool, info: dict | None) -> Step:
        """Start (append) a new step to the trajectory.

        Subclasses are encouraged to call this at the beginning of `update_from_env`
        to avoid relying on the implicit `steps[-1]` contract.

        Args:
            observation: Observation from environment.
            reward: Optional env/tool reward.
            done: Env done flag.
            info: Metadata.

        Returns:
            The newly created Step.
        """
        step = Step(
            # chat_completions must always be ConversationType.
            # Let subclasses decide how to convert observation into ConversationType.
            chat_completions=[],
            observation=observation,
            info=info or {},
            tool_reward=reward,
            done=done,
        )
        # TODO(linsh): check whether global steps are required
        self.session_data.steps.append(step)
        self.session_data.trajectories[-1].steps.append(step)
        return step

    @abstractmethod
    def format_chat_completions(self, observation: ObsType, *, is_init: bool) -> ConversationType:
        """Convert an environment observation into ConversationType for Step.chat_completions.

        Design notes:
        - Step.chat_completions is considered a normalized chat history format used by
          downstream tooling / debugging / logging, independent of the raw ObsType.
        - For non-chat environments, subclasses can choose any representation as long
          as it is a list of {"role": str, "content": str} dicts.

        Args:
            observation: Raw observation from environment (ObsType).
            is_init: Whether this is the first observation of the trajectory.

        Returns:
            ConversationType: a list of chat messages.
        """
        raise NotImplementedError

    def get_current_step(self) -> Step:
        """Get the current (latest) step.

        Raises a clearer error than an IndexError if subclasses call into
        step-dependent helpers before starting a step.
        """
        if len(self.session_data.steps) == 0:
            raise RuntimeError(
                "No step exists in trajectory yet. Ensure `update_from_env()` (or `start_step()`) "
                "is called before `update_from_model_*()` methods."
            )
        return self.session_data.steps[-1]

    def append_prompt_ids(self, prompt_ids: list[int]) -> None:
        """Set prompt token ids for the trajectory."""
        self.session_data.trajectories[-1].prompt_ids = list(prompt_ids)

    def append_user_tokens(self, token_ids: list[int]) -> None:
        """Append tokens that come from the environment/user side.

        These tokens should not be trained on, so response_mask is 0.
        Subclasses may override if they use a different masking scheme.
        """
        if not token_ids:
            return
        # Session-level stats
        self.session_data.user_turns += 1
        self.session_data.response_length += len(token_ids)

        # Trajectory-level stats
        self.session_data.trajectories[-1].user_turns += 1
        self.session_data.trajectories[-1].response_ids += list(token_ids)
        self.session_data.trajectories[-1].response_mask += [0] * len(token_ids)
        self.session_data.trajectories[-1].response_length += len(token_ids)
        if len(self.session_data.trajectories[-1].response_logprobs) > 0:
            # Keep alignment if logprobs are being tracked.
            self.session_data.trajectories[-1].response_logprobs += [0.0] * len(token_ids)

    def append_assistant_tokens(
        self,
        token_ids: list[int],
        logprobs: list[float] | None = None,
        routed_experts: list[int] | None = None,
    ) -> None:
        """Append tokens generated by the model/assistant side.

        Args:
            token_ids: Generated token ids.
            logprobs: Optional per-token logprob list aligned to token_ids.
        """
        if not token_ids:
            return
        # Session-level stats
        self.session_data.assistant_turns += 1
        self.session_data.response_length += len(token_ids)
        
        # Trajectory-level stats
        self.session_data.trajectories[-1].assistant_turns += 1
        self.session_data.trajectories[-1].response_ids += list(token_ids)
        self.session_data.trajectories[-1].response_mask += [1] * len(token_ids)
        self.session_data.trajectories[-1].response_length += len(token_ids)
        if logprobs:
            self.session_data.trajectories[-1].response_logprobs += list(logprobs)
        if routed_experts:
            self.session_data.trajectories[-1].routed_experts = routed_experts

    def set_step_action(self, action: ActType) -> None:
        """Set parsed action for the current step."""
        self.get_current_step().action = action

    def set_step_model_response(self, text: str) -> None:
        """Set raw model response text for the current step."""
        self.get_current_step().model_response = text

    def add_step_chat_message(self, message: dict[str, Any]) -> None:
        """Append a chat-format message into current step's chat completion list."""
        step = self.get_current_step()
        # Preserve backward compatibility: Step.chat_completions is a list.
        step.chat_completions.append(message)

    @abstractmethod
    def reset(self) -> None:
        """Reset the agent data to initial state.

        This method should clear any accumulated trajectory data and prepare
        the agent for a new episode. Must be implemented by subclasses.
        """
        return

    @abstractmethod
    async def encode_observation(self, observation: ObsType, *, is_init: bool = False) -> tuple[list[int], bool]:
        """Encode an environment observation into token IDs (async).

        Implementations should offload blocking tokenizer calls to the default
        executor (``asyncio.get_running_loop().run_in_executor(None, ...)``) so
        the event loop is not blocked.

        Default implementation indicates "not implemented" so subclasses can
        keep implementing `update_from_env` directly.

        Returns:
            (token_ids, is_prompt):
              - token_ids: token ids derived from observation
              - is_prompt: whether these ids should be treated as prompt_ids
        """
        raise NotImplementedError

    @abstractmethod
    def decode_action_from_token_ids(self, token_ids: list[int]) -> ActType:
        """Decode model-generated token ids into an environment action.

        Default isn't implemented so subclasses can keep implementing
        `update_from_model_token_ids` directly.
        """
        raise NotImplementedError

    def init_trajectory(self, request: Any) -> None:
        """Initialize a new trajectory based on the input request.

        Sets up the trajectory with initial metadata like request_id and parent_id.
        Subclasses should implement this to handle request-specific initialization.

        Args:
            request: Input request containing initial task information.

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError(f"{self.__class__.__name__} must implement init_trajectory method.")

    async def update_from_env(
        self,
        observation: ObsType,
        reward: float | list[float] | None,
        done: bool,
        info: dict,
        **kwargs,
    ) -> bool:
        """Update agent data from environment feedback.

        This method processes the environment's response after an action is taken,
        updating the trajectory with new observations and rewards.

        Args:
            observation: Observation received from the environment
            reward: Reward value from the environment (if applicable)
            done: Whether the episode has terminated
            info: Additional information from the environment
            **kwargs: Additional keyword arguments

        Returns:
            bool: True if the trajectory should be finalized, False otherwise

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError(f"{self.__class__.__name__} must implement update_from_env method.")

    async def update_from_model_token_ids(self, output: Any, **kwargs) -> tuple[ActType, bool]:
        """Update agent data from model token ids output.

        Processes raw token IDs generated by the model, extracting actions and
        updating the trajectory state accordingly.

        Args:
            output: Model output containing generated token IDs
            **kwargs: Additional keyword arguments

        Returns:
            tuple: (action, done) where action is the extracted action and done
                indicates if the trajectory should be finalized

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError(f"{self.__class__.__name__} must implement update_from_model_token_ids method.")

    def prepare_chat_completion_request(self) -> tuple[list[dict], list[dict] | None]:
        """Build (messages, tools) for the chat completion API.

        Returns:
            Tuple of (messages list, tools list or None).
        """
        raise NotImplementedError(f"{self.__class__.__name__} must implement prepare_chat_completion_request method.")

    async def update_from_model_chat_completion(self, output: Any, **kwargs) -> tuple[ActType, bool]:
        """Update agent data from model chat completion output.

        Processes structured chat completion output from the model, extracting
        actions and updating the trajectory state.

        Args:
            output: Model output in chat completion format
            **kwargs: Additional keyword arguments

        Returns:
            tuple: (action, done) where action is the extracted action and done
                indicates if the trajectory should be finalized

        Raises:
            NotImplementedError: Must be implemented by subclasses.
        """
        raise NotImplementedError(
            f"{self.__class__.__name__} must implement update_from_model_chat_completion method."
        )

    def update_trajectory_state_from_output(self, output: TokenOutput, **kwargs):
        """Update trajectory state based on model output dataproto."""
        self.session_data.curr_rollout_instance_id = output.rollout_instance_id
        self.get_current_step().info["rollout_instance_id"] = output.rollout_instance_id

    def prepare_generation_request(self, request: dict) -> dict:
        """Prepare the generation request based on the current agent data state.

        Args:
            request (dict): Original input request.

        Returns:
            dict: Modified request for generation.
        """
        request["raw_prompt_ids"] = np.array(self.session_data.trajectories[-1].prompt_ids)
        request["raw_response_ids"] = np.array(self.session_data.trajectories[-1].response_ids)
        if self.session_data.curr_rollout_instance_id is not None:
            request["rollout_instance_id"] = self.session_data.curr_rollout_instance_id
        
        # Propagate accumulated multi-modal data so generate_sequence() can
        # forward it to the inference backend on every turn.
        if (
            self.session_data.trajectories[-1].image_data is not None
            or self.session_data.trajectories[-1].video_data is not None
        ):
            mm: dict = {}
            if self.session_data.trajectories[-1].image_data is not None:
                mm["images"] = self.session_data.trajectories[-1].image_data
            if self.session_data.trajectories[-1].video_data is not None:
                mm["videos"] = self.session_data.trajectories[-1].video_data
            request["multi_modal_data"] = mm

        return request

    def compute_step_reward(self, step: Step) -> float:
        """
        Compute the step-level reward.
        Default: sum of tool_reward and model_reward

        Args:
            step: The step to compute the reward for.
        Returns:
            The computed step reward.
        """
        # TODO(linsh): find a better approach to handle multiple tool rewards
        # currently we just sum them up for trajectory-level reward computation,
        # but we may want to keep them separate for more detailed credit assignment.
        tool_reward = np.sum(step.tool_reward) if step.tool_reward is not None else 0.0
        model_reward = step.model_reward if step.model_reward is not None else 0.0
        step.reward = tool_reward + model_reward
        return step.reward

    def adjust_step_rewards(self, trajectory: Trajectory) -> None:
        """
        Adjust the step-level rewards using reward shaping and discounting.

        Applies two optional transformations:
        1. Reward shaping: Adds bonus based on reward differences between steps
        2. Monte Carlo returns: Computes discounted cumulative rewards

        Both transformations are disabled by default (coefficients = 0.0).

        Args:
            trajectory: The trajectory to adjust the rewards for.
        """
        # Reward shaping: add bonus proportional to reward deltas
        # Formula: s[i].reward = s[i].reward + bonus * (s[i].reward - s[i-1].reward) for i > 0
        if self.reward_bonus_coeff > 0.0:
            raw_rewards = [step.reward for step in trajectory.steps]
            for i in range(1, len(trajectory.steps)):
                trajectory.steps[i].reward += self.reward_bonus_coeff * (raw_rewards[i] - raw_rewards[i - 1])

        # Compute Monte Carlo returns (backward iteration)
        # Formula: G_t = R_{t+1} + γ * R_{t+2} + γ² * R_{t+3} + ... + γ^{T-t-1} * R_T
        if self.gamma > 0.0:
            G = 0.0
            for step in reversed(trajectory.steps):
                G = step.reward + self.gamma * G
                step.reward = G  # Replace the reward with MC return

    async def finalize_output(self) -> TokenOutput | list[TokenOutput] | None:
        """Finalize the trajectory and prepare output for reward computation."""
        response_length = self.config.gen_actor_rollout_ref.rollout.response_length

        outputs = []
        for trajectory in self.session_data.trajectories:
            trajectory.response_ids = trajectory.response_ids[: response_length]
            trajectory.response_mask = trajectory.response_mask[: response_length]
            trajectory.response_logprobs = trajectory.response_logprobs[: response_length]
            
            multi_modal_data = None
            if trajectory.image_data is not None or trajectory.video_data is not None:
                multi_modal_data = {}
                if trajectory.image_data is not None:
                    multi_modal_data["images"] = trajectory.image_data
                if trajectory.video_data is not None:
                    multi_modal_data["videos"] = trajectory.video_data
            
            output: TokenOutput = TokenOutput(
                prompt_ids=trajectory.prompt_ids,
                response_ids=trajectory.response_ids,
                response_mask=trajectory.response_mask,
                response_log_probs=(
                    trajectory.response_logprobs
                    if len(trajectory.response_logprobs) > 0
                    else None
                ),
                routed_experts=(
                    trajectory.routed_experts[: len(trajectory.prompt_ids) + response_length]
                    if len(trajectory.routed_experts) > 0
                    else None
                ),
                multi_modal_data=multi_modal_data,
                # TODO(linsh): check whether use global num_turns
                num_turns=self.session_data.assistant_turns + self.session_data.user_turns + 1,
                rollout_instance_id=self.session_data.curr_rollout_instance_id,
                extra_fields={
                    "tool_rewards": trajectory.tool_rewards,
                    "turn_scores": trajectory.turn_scores,
                }
            )
            outputs.append(output)
        
        if self.config.gen_actor_rollout_ref.rollout.agent.traj_reward_mode == "step":
            assert not self.config.reward.launch_reward_fn_async, (
                "Asynchronous reward computation is not supported in 'step' traj_reward_mode."
            )
            for trajectory, output in zip(self.session_data.trajectories, outputs):
                trajectory.reward = np.sum([self.compute_step_reward(step) for step in trajectory.steps])
                if len(trajectory.steps) > 1:
                    self.adjust_step_rewards(trajectory)
                output.reward_score = trajectory.reward
        elif self.config.gen_actor_rollout_ref.rollout.agent.traj_reward_mode == "traj":
            # NOTE(linsh): Only compute reward for the last trajectory.
            final_output = outputs[-1]
            tensor_dict = {
                "prompts": torch.tensor(final_output.prompt_ids, dtype=torch.int64).unsqueeze(0),
                "responses": torch.tensor(final_output.response_ids, dtype=torch.int64).unsqueeze(0),
                "multi_modal_data": np.array([final_output.multi_modal_data], dtype=object),
                "num_turns": np.array([final_output.num_turns]),
                "tool_extra_fields": np.array([final_output.extra_fields], dtype=object),
                "uid": np.array([self.session_data.request_id]),
                "n_trajectory": np.array([len(outputs)]),
                "data_source": np.array([self.session_data.data_source]),
                "reward_model": np.array([self.session_data.reward_model], dtype=object),
                "extra_info": np.array([self.session_data.extra_info], dtype=object),
                "reward_model_dicts": np.array([self.session_data.reward_model_dicts], dtype=object),
            }
            if self.session_data.parent_id is not None:
                tensor_dict["parent_id"] = np.array([self.session_data.parent_id])

            reward_data = tu.get_tensordict(
                tensor_dict=tensor_dict,
                non_tensor_dict={
                    "validate": self.session_data.validate,
                },
            )

            reward_result = await self.reward_manager.compute_score.remote(reward_data)
            if not self.config.reward.launch_reward_fn_async:
                if not reward_result:
                    return None
                # Broadcast to all trajectories
                for output in outputs:
                    output.reward_score = reward_result["reward_score"]
                    output.extra_fields["reward_extra_info"] = reward_result["reward_extra_info"]
                    output.extra_fields["reward_metrics"] = reward_result.get("reward_metrics", {})
        else:
            raise ValueError(
                f"Unknown traj_reward_mode: {self.config.gen_actor_rollout_ref.rollout.agent.traj_reward_mode}"
            )

        if len(outputs) == 1:
            return outputs[0]
        return outputs

    @classmethod
    def get_agent_data(cls, name: str, *args, **kwargs) -> "AgentData":
        """
        Get an agent data instance by name from the registry.

        Args:
            name: The name of the agent data to retrieve
            *args: Positional arguments to pass to the agent data constructor
            **kwargs: Keyword arguments to pass to the agent data constructor

        Returns:
            AgentData: An instance of the requested agent data

        Raises:
            ValueError: If the agent data is not found in the registry
        """
        if name not in cls._registry:
            raise ValueError(f"Unknown agent data: {name}")
        return cls._registry[name](*args, **kwargs)

    @classmethod
    def register(cls, name: str):
        """
        Decorator to register an agent data class with the registry.

        Args:
            name: The name to register the agent data under

        Returns:
            The decorator function

        Example:
            @AgentData.register("tool_agent_data")
            class ToolAgentData(AgentData):
                def reset(self):
                    # implementation
                    pass
        """

        def decorator(subclass: type["AgentData"]) -> type["AgentData"]:
            cls._registry[name] = subclass
            return subclass

        return decorator
