# Method for proactive filter strategy
# Available options: "null", "retry", "truncate"
method: null

# Threshold of retry/truncate requests per buffer
# When the buffer is not ready but the training side is waiting for it
# We will trigger the retry/truncate strategy when the number of remaining reserved entries is smaller than this value
threshold: 0
