# Post processor for group requests in streaming mode

# Whether to enable group post-processing
enable: False

# Name of the registered group post-processor to use
# Available options: "dynamic_sampling_filter", "no_filter"
# When name is "dynamic_sampling_filter", requires algorithm.filter_groups.metric to be set
name: null
