defaults:
  - rollout_coordination/routing_strategy@rollout_coordination.routing_strategy
  - rollout_coordination/sync_and_mig_strategy@rollout_coordination.sync_and_mig_strategy
  - rollout_coordination/partial_rollout@rollout_coordination.partial_rollout
  - rollout_coordination/redundant_rollout@rollout_coordination.redundant_rollout
  - rollout_coordination/proactive_filter_strategy@rollout_coordination.proactive_filter_strategy
  - rollout_coordination/session_strategy@rollout_coordination.session_strategy
  - deployment@deployment
  - fine_grain_overlap@fine_grain_overlap
  - agentic_rl@agentic_rl
  - server_rollout@server_rollout
  - profile@profile
  - log_prob@log_prob
  - status_collection@status_collection
  - memory_logger@memory_logger
  - nixl@nixl
  - broadcast_init@broadcast_init
  - checkpoint@checkpoint
  - group_post_process@group_post_process
  - buffer_post_process@buffer_post_process
  - tms@tms
  - lmcache@lmcache
  - rollout_gateway@rollout_gateway
  - _self_

# IP address of parameter server managaer.
ps_manager_ip: 127.0.0.1

# IP address of reward service.
reward_service_ip: ${psrl.ps_manager_ip}

# Staleness control of training data.
staleness: 0

# Size of each staleness buffer (i.e. training batch)
staleness_buffer_entries: 512

# number of responses (i.e. num sample times). > 1 for grpo
rollout_n: 1

# Weight synchronization mode for parameter server: cpu_ref or nixl_cpu
ps_mode: cpu_ref

# Logging path
logging_path: ~/psrl_logs

# Buffer bound for retry mechanism
retry_bound: -1

# Ratio over retry bound
retry_ratio: 1.0

# Whether to colocate validate and training workers
colocate_validate_and_train: True

# Whether to dispatch requests to both rollout and validate instances
fuse_rollout_with_validate: True
